### ISSUE TITLE
Изучить доступные в мире .NET методы анализа текста

### ISSUE THREAD

**Issue by gbagretsov** [nshindarev/SEA-SocNetwork#2]
Возможно, Naive Bayes или tf-idf

**Comment by nshindarev** [comment]
Ну что, изучил?

**Comment by gbagretsov** [comment]
Наверное, буду использовать Azure Machine Learning

**Comment by gbagretsov** [comment]
Всё-таки Accord.NET с найденной либой про tf-idf, но возможно, одного метода не хватит, поэтому пока открою снова

**Comment by gbagretsov** [comment]
Хватило
