### ISSUE TITLE
Разделить Model на AuthorizationModel и MainFormModel

### ISSUE THREAD

**Issue by nshindarev** [nshindarev/SEA-SocNetwork#4]
На данный момент всё крашится из-за того, что для presenter фабрика выдаёт новый экземпляр модели в MainForm, в следствие чего мы не запоминаем user_id и access_token

**Comment by gbagretsov** [comment]
Тебе не нужно запоминать access_token, он хранится в VkNet после авторизации. А user_id можно получить из него же, есть там какой-то метод. Другое дело, что пользователь может захотеть разлогиниться, но это уже другой вопрос.

**Comment by nshindarev** [comment]
Я знаю, это все ещё относится к рефакторингу

пн, 28 нояб. 2016 г. в 20:58, Georgiy Bagretsov <notifications@github.com>:
